version: '3'

services:
  db:
    container_name: pos_system-db
    image: postgres
    environment:
      - POSTGRES_DB=pos_system

  web:
    container_name: pos_system-web
    build: .
    volumes:
      - .:/pos_system
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
