# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(to='pos_app.Items')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
