# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name_plural': 'Receipts'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
